%% Segment the Foreground
% For this problem you will be assessed using a randomly chosen selection from 
% the three test images, so it is a good idea to test your algorithm on each of 
% them in MATLAB before submitting here. 
%% 
% * Your code will need to create a mask to accurately segment the foreground 
% (both the coins and blanks) from the background. Use variable name |*testCoinMask*|.
% * Depending on how you segmented the image with all valid coins, the same 
% code may work here, but you'll need to test it to be sure. 

testImageIdx = randi([1,3]);
testCoinImage = imread("testCoinImage"+testImageIdx+".png");
figure, imshow(testCoinImage)
testCoinImage = imread("testCoinImage3.png");
[coinMask,testCoinMask] = segmentCoin(testCoinImage);
montage({testCoinMask,testCoinImage});


%%
function [coinMask,testCoinMask] = segmentCoin(X)
%segmentImage Segment image using auto-generated code from Image Segmenter app
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the Image Segmenter app. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 31-Dec-2022
%----------------------------------------------------
X = im2gray(X);

% Threshold image - manual threshold
coinMask = im2gray(X) > 188;

% Close mask with default
radius = 10;
decomposition = 0;
se = strel('disk', radius, decomposition);
coinMask = imclose(coinMask, se);

% Create masked image.
testCoinMask = X;
testCoinMask(~coinMask) = 0;
testCoinMask = testCoinMask > 100;
end